import type { NextPage } from 'next'
import Head from 'next/head'
import Form from "../components/Forms/Form";
import HookForm from "../components/Forms/HookForm";
import { myFormInputs, myHookFormInputs } from "../InputsData/inputs";

import styles from '../styles/Home.module.css'


const myFormProps = {
    gap: '10px',
    padding: '20px 30px'
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div style={{display: 'flex', flexDirection: 'row', justifyContent: 'space-between', width: '80vw'}}>
            <div>
                <h1>Кастомная форма</h1>
                <Form
                    inputs={myFormInputs}
                    gap={myFormProps.gap}
                    padding={myFormProps.padding}
                    button='Отправить'
                >
                </Form>
            </div>

            <div>
                <h1>react-hook-form форма</h1>
                <HookForm
                    inputs={myHookFormInputs}
                    gap={myFormProps.gap}
                    padding={myFormProps.padding}
                    button='Отправить'
                />
            </div>
        </div>
    </div>
  )
}

export default Home
